### ISSUE TITLE
[LSP] Format request failed, no matching language servers.

### ISSUE THREAD

**Issue by ARS101** [Pakrohk-DotFiles/NvPak#34]
**Describe the bug:**
I get this warning:
```[LSP] Format request failed, no matching language servers.```

**To reproduce**
Open a python file using nvim

**Expected behavior**
No warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/121791251/215264219-5d790551-82a0-40e2-b2f2-2c49ae1f8b1e.png)

**Informations**
- OS: Fedora 37 stable
- NVIM version: 0.8.2
- Latest commit: 0d71e212f446911daafc204481c16018d9185d8f

**Comment by ALipAkrohk** [comment]
Checked and the problem was solved.
Now you can format your codes in two ways.
1- Tell null-ls how to do it, and every time the code is saved, it will be automatically formatted.
2- Introduce the formatter package to mason-null-ls (for example, you can use black for Python) and format your code by pressing space + f.

**Comment by ARS101** [comment]
Can confirm. It's solved.
